services:
  app:
    build:
      context: .
      args:
        - DEV="true"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.venv
    environment:
      - DB_HOST=db
      - DB_NAME=recipesDB
      - DB_USER=postgres
      - DB_PASSWORD=supersecret123
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=recipesDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecret123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  dev-db-data:
